'use client';
export const shared = { ['/react/index.js']: 'react',
['__remote_shared_module_react']: () => import('react'),
['/react/jsx-dev-runtime.js']: 'react/jsx-dev-runtime',
['__remote_shared_module_react/jsx-dev-runtime']: () => import('react/jsx-dev-runtime'),
['/react/jsx-runtime.js']: 'react/jsx-runtime',
['__remote_shared_module_react/jsx-runtime']: () => import('react/jsx-runtime'),
['/react-dom/index.js']: 'react-dom',
['__remote_shared_module_react-dom']: () => import('react-dom'),
['node_modules/.pnpm/react-dom@19.2.3_react@19.2.3/node_modules/react-dom/client.js']: 'react-dom/client',
['__remote_shared_module_react-dom/client']: () => import('react-dom/client'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/navigation.js']: 'next/navigation',
['__remote_shared_module_next/navigation']: () => import('next/navigation'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/dist/client/components/navigation.js']: 'next/dist/client/components/navigation',
['__remote_shared_module_next/dist/client/components/navigation']: () => import('next/dist/client/components/navigation'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/link.js']: 'next/link',
['__remote_shared_module_next/link']: () => import('next/link'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/dist/client/app-dir/link.js']: 'next/dist/client/app-dir/link',
['__remote_shared_module_next/dist/client/app-dir/link']: () => import('next/dist/client/app-dir/link'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/form.js']: 'next/form',
['__remote_shared_module_next/form']: () => import('next/form'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/dist/client/app-dir/form.js']: 'next/dist/client/app-dir/form',
['__remote_shared_module_next/dist/client/app-dir/form']: () => import('next/dist/client/app-dir/form'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/image.js']: 'next/image',
['__remote_shared_module_next/image']: () => import('next/image'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/dist/client/image-component.js']: 'next/dist/client/image-component',
['__remote_shared_module_next/dist/client/image-component']: () => import('next/dist/client/image-component'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/dist/api/image.js']: 'next/dist/api/image',
['__remote_shared_module_next/dist/api/image']: () => import('next/dist/api/image'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/script.js']: 'next/script',
['__remote_shared_module_next/script']: () => import('next/script'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/dist/client/script.js']: 'next/dist/client/script',
['__remote_shared_module_next/dist/client/script']: () => import('next/dist/client/script'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/dist/build/polyfills/process.js']: 'next/dist/build/polyfills/process',
['__remote_shared_module_next/dist/build/polyfills/process']: () => import('next/dist/build/polyfills/process'),};
