'use client';
export const shared = { ['/react/index.js']: 'react',
['__remote_shared_module_react']: () => import('react'),
['/react/jsx-dev-runtime.js']: 'react/jsx-dev-runtime',
['__remote_shared_module_react/jsx-dev-runtime']: () => import('react/jsx-dev-runtime'),
['/react/jsx-runtime.js']: 'react/jsx-runtime',
['__remote_shared_module_react/jsx-runtime']: () => import('react/jsx-runtime'),
['/react-dom/index.js']: 'react-dom',
['__remote_shared_module_react-dom']: () => import('react-dom'),
['node_modules/.pnpm/react-dom@19.2.3_react@19.2.3/node_modules/react-dom/client.js']: 'react-dom/client',
['__remote_shared_module_react-dom/client']: () => import('react-dom/client'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/router.js']: 'next/router',
['__remote_shared_module_next/router']: () => import('next/router'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/link.js']: 'next/link',
['__remote_shared_module_next/link']: () => import('next/link'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/image.js']: 'next/image',
['__remote_shared_module_next/image']: () => import('next/image'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/script.js']: 'next/script',
['__remote_shared_module_next/script']: () => import('next/script'),
['node_modules/.pnpm/next@16.1.1_@babel+core@7.29.0_@opentelemetry+api@1.9.0_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/form.js']: 'next/form',
['__remote_shared_module_next/form']: () => import('next/form'),};
